import { Lato, Open_Sans } from "next/font/google";
import "@/styles/styles.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-lato",
});
const open_Sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata = {
  title: "Headless Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${open_Sans.className} ${open_Sans.variable} ${lato.variable}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
